image: go1.2
notify:
  email:
    recipients:
    - drone@clever.com
  slack:
    on_failure: true
    on_started: false
    on_success: false
    webhook_url: $$slack_webhook
publish:
  docker:
    docker_file: Dockerfile
    docker_server: $$docker_server
    email: $$email
    image_name: clever/riemann-gearman
    password: $$password
    registry_login: true
    tags:
    - $(git rev-parse --short HEAD)
    username: $$username
    when:
      branch: master
script:
- make test
