image: go1.2
script:
  - make test
notify:
  email:
    recipients:
      - drone@clever.com
  hipchat:
    room: Clever-Dev-CI
    token: {{hipchatToken}}
    on_started: true
    on_success: true
    on_failure: true
publish:
  docker:
    docker_file: Dockerfile
    docker_server: {{docker_server}}
    docker_port: 4243
    docker_version: 0.10.0
    repo_base_name: clever
    username: {{username}}
    password: {{password}}
    email: {{email}}
    branch: master
